/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yumt_zksoft_ZKTCP_CPP */

#ifndef _Included_com_yumt_zksoft_ZKTCP_CPP
#define _Included_com_yumt_zksoft_ZKTCP_CPP
#ifdef __cplusplus
extern "C" {
#endif
	namespace ZKTCP{
		JNIEXPORT BOOL JNICALL Connect_Net(LPCTSTR lpnativeAddress,int port);
		JNIEXPORT BOOL JNICALL ReadAllGLogData(DWORD dwMachineNumber);
		JNIEXPORT BOOL JNICALL GetGeneralLogDataStr ( long dwMachineNumber, long * dwEnrollNumber, long * dwVerifyMode, long * dwInOutMode, BSTR * TimeStr ) ;
		JNIEXPORT LPCTSTR JNICALL GetALLGeneralLogData_withJson( long dwMachineNumber);
		JNIEXPORT LPCTSTR JNICALL GetAllUserInfo_WithJson(long dwMachineNumber);
		JNIEXPORT BOOL JNICALL ClearGLog ( long dwMachineNumber );
		JNIEXPORT BOOL JNICALL ReadAllUserID ( long dwMachineNumber );
		JNIEXPORT BOOL JNICALL GetAllUserInfo ( long dwMachineNumber, long * dwEnrollNumber, BSTR * Name, BSTR * Password, long * Privilege, VARIANT_BOOL * Enabled ) ;
		JNIEXPORT BOOL JNICALL GetUserInfo ( long dwMachineNumber, long dwEnrollNumber, BSTR * Name, BSTR * Password, long * Privilege, VARIANT_BOOL * Enabled ) ;
		JNIEXPORT BOOL JNICALL SetUserInfo ( long dwMachineNumber, long dwEnrollNumber, BSTR Name, BSTR Password, long Privilege, VARIANT_BOOL Enabled ) ;
		JNIEXPORT BOOL JNICALL SetUserTmpStr ( long dwMachineNumber, long dwEnrollNumber, long dwFingerIndex, BSTR TmpData ) ;
		JNIEXPORT BOOL JNICALL GetUserTmpStr ( long dwMachineNumber, long dwEnrollNumber, long dwFingerIndex, BSTR * TmpData, long * TmpLength ) ;
		JNIEXPORT void JNICALL Disconnect();	
		JNIEXPORT void JNICALL EnableDevice(LONG dwMachineNumber,VARIANT_BOOL Enabled);
		JNIEXPORT BOOL JNICALL GetGeneralLogData ( long dwMachineNumber, long * dwTMachineNumber, long * dwEnrollNumber, long * dwEMachineNumber, long * dwVerifyMode, long * dwInOutMode, long * dwYear, long * dwMonth, long * dwDay, long * dwHour, long * dwMinute,long *dwSecond ) ;	

	}
#ifdef __cplusplus
}
#endif
#endif
